name: Build and deploy master branch
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh-mi
          server-username: OSSRH_USERNAME_MI
          server-password: OSSRH_TOKEN_MI
      - name: Maven deploy package
        run: mvn --batch-mode deploy
        env:
          OSSRH_USERNAME_MI: ${{ secrets.OSSRH_USERNAME_MI }}
          OSSRH_TOKEN_MI: ${{ secrets.OSSRH_TOKEN_MI }}
